version: '3.3'

services:
  database:
    image: mysql:5.7
    volumes:
      - database_data:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.30.0.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ee5058ec-da12-4903-abfc-9b2f5eb32f7d
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    networks:
      backend:
        ipv4_address: 172.30.0.3
    restart: always
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

networks:
  backend:
    external: true

volumes:
  database_data: {}
